### ISSUE TITLE
Hintergrundbilder

### ISSUE THREAD

**Issue by nichtich** [jakobib/bibtag2022#2]
PDF oder HTML? Die Hintergrundbilder sind nur in HTML vorhanden und im Abschnitt "Ausblick" fehlt ein Bild.

**Comment by nwagner84** [comment]
Ich habe jetzt erstmal nur mit der PDF-Version gearbeitet, da bei mir revealjs gefehlt hat. In die PDF-Version lassen sich die Hintergrundbilder nicht einbinden (mir fehlt hier leider etwas Erfahrung mit pandoc)?
